### ISSUE TITLE
Invalid config file name

### ISSUE THREAD

**Issue by raminious** [apizzimenti/cli-weather#10]
Hi
thanks for your great app
but you must change 

```
config = require('./lib/Config');
```

to 

```
config = require('./lib/config');
```

Because unix based systems are case sensitive and the app not running on linux until I changed to name of config file

**Comment by pizzimathy** [comment]
okie doke, no problem.

**Comment by pizzimathy** [comment]
v1.3.4, this issue should be fixed.
