### ISSUE TITLE
Hide unnecessary messages

### ISSUE THREAD

**Issue by ScheerMT** [apizzimenti/cli-weather#12]
The majority of the time people aren't interested in seeing when something in the background just works.. They are interested in the errors! 

What I propose is to hide the first 3-4 lines that contain the checkmarks whenever something completes. These could be viewed by an additional argument `-v` or `--verbose`.

The steps where it says it is saving a location would still be useful to always have displayed along with any errors that occur. 

Thoughts?

**Comment by pizzimathy** [comment]
Should I add a preset that allows them to be seen, or a preset that allows them to be hidden?

Basically, sould they be visible by default or hidden by default? From your question, I assume the latter.

**Comment by ScheerMT** [comment]
Your assumption is correct. Hidden by default unless the message is pertinent to another argument (saving a location for example) or if an error occurs. The success messages are nice but only needed for debugging errors IMO

**Comment by pizzimathy** [comment]
Yeah, that's true. I was just using them for debug purposes and people didn't really have an issue with it and so I left them in.

**Comment by jwhitmarsh** [comment]
+1 - language standard is to include a `--verbose` flag

**Comment by tielur** [comment]
+1 awesome little tool though!
