### ISSUE TITLE
Maximum call stack size exceeded on installation

### ISSUE THREAD

**Issue by sboselli** [apizzimenti/cli-weather#15]
I'm not being able to install, keep getting a "Maximum call stack size exceeded".

Has anyone experienced something similar?

I'm using node v.4.2.2 and npm v.3.5.2.

And, here are the last few lines of my npm-debug.log

11888 silly build update-notifier@0.6.0
11889 info linkStuff update-notifier@0.6.0
11890 silly linkStuff update-notifier@0.6.0 has /usr/lib/node_modules/cli-weather/node_modules as its parent node_modules
11891 silly linkStuff update-notifier@0.6.0 is part of a global install
11892 silly linkStuff update-notifier@0.6.0 is installed into a global node_modules
11893 verbose linkBins update-notifier@0.6.0
11894 verbose linkMans update-notifier@0.6.0
11895 silly build cli-weather@1.3.73
11896 info linkStuff cli-weather@1.3.73
11897 silly linkStuff cli-weather@1.3.73 has /usr/lib/node_modules as its parent node_modules
11898 silly linkStuff cli-weather@1.3.73 is part of a global install
11899 silly linkStuff cli-weather@1.3.73 is installed into a global node_modules
11900 silly linkStuff cli-weather@1.3.73 is installed into the top-level global node_modules
11901 verbose linkBins cli-weather@1.3.73
11902 verbose link bins [ { weather: 'index.js' }, '/usr/bin', true ]
11903 verbose linkMans cli-weather@1.3.73
11904 silly gentlyRm /usr/bin/weather is being gently removed
11905 verbose stack RangeError: Maximum call stack size exceeded
11905 verbose stack     at Array.filter (native)
11905 verbose stack     at /usr/lib/node_modules/npm/lib/install/actions.js:55:37
11905 verbose stack     at Array.forEach (native)
11905 verbose stack     at markAsFailed (/usr/lib/node_modules/npm/lib/install/actions.js:54:16)
11905 verbose stack     at /usr/lib/node_modules/npm/lib/install/actions.js:57:7
11905 verbose stack     at Array.forEach (native)
11905 verbose stack     at markAsFailed (/usr/lib/node_modules/npm/lib/install/actions.js:54:16)
11905 verbose stack     at /usr/lib/node_modules/npm/lib/install/actions.js:57:7
11905 verbose stack     at Array.forEach (native)
11905 verbose stack     at markAsFailed (/usr/lib/node_modules/npm/lib/install/actions.js:54:16)
11906 verbose cwd /home/santiago
11907 error Linux 3.13.0-68-generic
11908 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "cli-weather" "-g"
11909 error node v4.2.2
11910 error npm  v3.5.2
11911 error Maximum call stack size exceeded
11912 error If you need help, you may report this error at:
11912 error     https://github.com/npm/npm/issues
11913 verbose exit [ 1, true ]

**Comment by pizzimathy** [comment]
I'll take a look at it. Thanks for letting me know!

**Comment by pizzimathy** [comment]
do you use `sudo` to install?
