### ISSUE TITLE
Make the Forecast.io API key configurable

### ISSUE THREAD

**Issue by fmbenhassine** [apizzimenti/cli-weather#19]
Hi,

Thank you for sharing this nice project! :+1: 

Looks like the API key for forecast.io is [hardcoded](https://github.com/apizzimenti/cli-weather/blob/master/lib/args.js#L13). What if I want to use my own key? Any plan to make it configurable? I can open a pull request if you agree.

Kind regards
Mahmoud

**Comment by pizzimathy** [comment]
Yes, go ahead and open a pr. I'd like to see how you implement this, as I hadn't thought of allowing the client to change the API key. Good idea, thanks for offering.
