### ISSUE TITLE
Show temperature in celsius

### ISSUE THREAD

**Issue by Foxhunt** [apizzimenti/cli-weather#2]
Hi,

saw this on /r/node. Can you add a Celsius option?

**Comment by pizzimathy** [comment]
Yep, I'll add a feature/celsius branch.

**Comment by wevanscfi** [comment]
I can do this if you like.

**Comment by pizzimathy** [comment]
Yeah, that'd be nice. Maybe just a `Number.prototype.toCels = function (val)` kinda deal. This way, we can pass the `Format` object another parameter (a boolean, probably) that'll allow us to go like this:

```
// args.js
var Format = require('./Format'),
    weather = Format(json, true);

// Format.js
function Format(json, type) {
    this.celsius = type;
    ...
}

// data.js
Number.prototype.toCels = function (val) {
    if (val) {
        return this ... <convert to Celsius here>;
    } else {
        return this;
    }
}
```

That way we can just apply the toCels(val) method on any number (_any_ number) we want to convert, with `val = this.celsius` as the parameter.

Sound good?
