### ISSUE TITLE
Ambiguous test code

### ISSUE THREAD

**Issue by StdioA** [apizzimenti/cli-weather#20]
https://github.com/apizzimenti/cli-weather/blob/master/test/test-config.js#L21-L28

I don't think this test code can test anything.:expressionless:
Please check it out. Thx.

**Comment by pizzimathy** [comment]
Yep, totally agree. I've been writing unit tests on a separate branch, but
have yet to push them as I've been on other projects for a while. I'll keep
working on it and get it up ASAP.
