### ISSUE TITLE
Zipcode support

### ISSUE THREAD

**Issue by Zodiase** [apizzimenti/cli-weather#21]
I'm not sure if it makes a difference to the data source of your choice, but in some weather apps I've used, different zip codes within a city/county could result in completely different weather forecasts, like sunny here but stormy across the street.

Even if using zip code makes no improvement on accuracy, I find it easier to type in the zip code than the full name of the city.

CLI could be `weather -zip 12345`.

**Comment by pizzimathy** [comment]
I could add it as a feature. I am planning to start doing a rewrite of the module in (possibly in TypeScript) to make it a bit cleaner and add/remove features.

If you want, you can write it yourself and open a pull request. Otherwise, I can get to it sometime in the near future 😄

**Comment by pizzimathy** [comment]
@Zodiase I've added in a zipcode feature that can be invoked using `-z <zipcode>`. If you have any more issues/ideas, keep suggesting them 😄  the zipcode idea was great.

Thanks!

**Comment by CaioBianchi** [comment]
Could this functionality somehow be expanded into supporting Canadian postal codes, based on the `--can` option?
