### ISSUE TITLE
Table starts from tomorrow?

### ISSUE THREAD

**Issue by Zodiase** [apizzimenti/cli-weather#22]
Here's what I got:

![image](https://cloud.githubusercontent.com/assets/1815174/14892915/c775aa14-0d32-11e6-8c64-bc5d38ff5ec8.png)

My question is, why does the data in table start from Friday (while today is Thursday in my time zone)?

At first I think maybe it's because today's info is already displayed at top, but no the data at top is not of the same kind as the ones in the table at all.

Nobody is interested in today's high and low, and maybe precipitation probability?

**Comment by pizzimathy** [comment]
I didn't include today's forecast in the table because I wanted to get five days in, but then the table was too large for the default Terminal window, so I dropped today's forecast out of the table.

So should today's weather predictions be included in the table? It's meant to forecast the _next_ four days (excluding today), and this is done on purpose but is easily changed.

**Comment by Zodiase** [comment]
In my opinion, today should be part of the forecast and it's easily the most needed info, maybe just second to the forecast of tomorrow. The accuracy of weather forecasts decreases greatly as the time moves further from now, so the if I were to assign values to each day's forecast, considering how much people need it and how much people can rely on it, I would say `4.5, 5, 3, 2, 1`, where lower value means I'd be more OK if the value is missing or wrong. In that sense, if I had to throw away one piece of the data to make everything fit in the display window, I would pick the fifth day's data. Or, better, I could let people decide how many days to display, considering that I can stretch the Terminal window to fit. But maybe that's too much work for a non-essential feature.

**Comment by pizzimathy** [comment]
Would a feature allowing someone to pick the number of days for which the weather is reported? i.e. passing an argument like `-d <num>`, where `num` is the amount of days to go into the future (num can range from 1-5)?

If not, I can just shift the last day out and put today's in, like you said.

**Comment by pizzimathy** [comment]
Changed the range.
