### ISSUE TITLE
Not working on Debian

### ISSUE THREAD

**Issue by Noneatme** [apizzimenti/cli-weather#24]
I installed cli-weather via npm.

I got 4 warnings, but nothing critical.

These are the results when I execute weather:

`noneatme@noneatme:~$ sudo weather -z 90210`
`noneatme@noneatme:~$ sudo weather -a "Atlanta, GA"`

Actually nothing happens.
`noneatme@noneatme:~$ uname -a`
`Linux noneatme 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`

Any ideas?

**Comment by pizzimathy** [comment]
Just for clarification, what were the warnings? And if you try to run `weather` without `sudo`, what happens?

**Comment by Noneatme** [comment]
There are no warnings. The command does nothing with sudo.

When I execute weather without sudo, I'll get:

`/usr/bin/env: node: No such file or directory`

/EDIT: I fixed this issue by installing nodejs-legacy over node.

Thanks for your help!

**Comment by apizzimenti** [comment]
I've pushed a change that edits the shebang line. Let me know if it works.
