### ISSUE TITLE
(node:6145) DeprecationWarning - Buffer in node v7 

### ISSUE THREAD

**Issue by windyinsc** [apizzimenti/cli-weather#25]
The forecast continues to output correctly but prior to printing out I'm getting this node Buffer deprecation warning. FYI... This is with node v7.

```bash
(node:6145) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
```

If this helps, here are the results of `node --trace-deprecation server` 

```bash
module.js:474
    throw err;
    ^

Error: Cannot find module '/Users/user/server'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

**Comment by pizzimathy** [comment]
Sorry it took me so long to get to this, but I'll try and get a hotfix out soon.

**Comment by windyinsc** [comment]
@apizzimenti Just a friendly follow up. I'm no longer getting the error. Currently running node v7.3.0

**Comment by pizzimathy** [comment]
Awesome :) I've been working on a few new things (hint hint 😉) and I'm writing newer, better test code to better deal with all the data buffers. Glad to hear that everything is resolved, and I hope it stays that way.

Thanks, as always, for your input - it really makes this process easier.
