### ISSUE TITLE
Retrieve weather using longitude and latitude coordinates

### ISSUE THREAD

**Issue by windyinsc** [apizzimenti/cli-weather#39]
Love the update!!! I just wanted to point out to others that you can still retrieve weather using latitude & longitude coordinates.  Quick example... `weather -a 41.6627,-91.5549`

@apizzimenti please consider updating the documentation to include **lat,lon** within the `-a` options usage description(s).

**Comment by pizzimathy** [comment]
Hey @windyinsc! Nice seeing you in my gh notifications again 😃 I'll add this to the list of documentation to-dos for version 2.0.5. Thanks for pointing this out - I didn't even realize that the Google geocoder api took in arguments for latitude and longitude. Once the docs are updated, I'll close the ticket.

**Comment by pizzimathy** [comment]
Everything was added to the docs, I just forgot to let you know 😅  2.0.5 is out and includes helptext for adding lat/long coordinates.
