### ISSUE TITLE
Add configs to prevent needing to send the same arguments multiple times

### ISSUE THREAD

**Issue by snollygolly** [apizzimenti/cli-weather#6]
If you always want to see your weather with specific arguments passed to it, enable a way to save those arguments as a preset and pass them in without manually typing.

**Comment by ryanrishi** [comment]
One way to do this is to create an alias. If you just put this line in your ~/.bashrc, ~/.profile, or ~/.bash_profile:

alias weather='weather -c -a "New York"'

that will do exactly as you wish.

**Comment by pizzimathy** [comment]
I've merged in snollygolly's branch and pushed here as well as published to npm.
